export const english = {
  welcomeIntro: "A place where even -you- can find a friend.",
  login: "Login",
  signup: "Sign Up",
  orContinueWith: "Or continue with",
  newHere: "Don't have an account ?",
  alreadyHave: "Already have an account?",
  register: "Register",
  signIn: "Sing In",
  createAccount: "Create an Account",
  yourUsername: "Your Username",
  emailAdress: "Email Address",
  exampleMail: "example@xyz.com",
  yourPassword: "Your Password",
  createPassword: "Create a password for your security",
  unsupportedEnv:
    "Unsupported environment. Update your browser or app, or visit the official site to log in.",
  appUser: "OchoApp User",
  language: "Language",
  search: "Search",
  searches: "Search",
  searchResultFor: 'Search results for "[q]".',
  noSearchResultFor: 'No result for "[q]".',
  searchEmptyKeyword: "Please enter keywords in your search",
  tryNewSearch: "Try a new search.",
  users: "Users",
  searchUsers: "Search users",
  loggedIn: "Logged in as",
  profile: "Profile",
  theme: "Theme",
  systemDefault: "System (default)",
  system: "System",
  light: "Light",
  dark: "Dark",
  logout: "Logout",
  home: "Home",
  explore: "Explore",
  notifications: "Notifications",
  activity: "Activity",
  activityCenter: "Activity Center",
  noActivity: "Your activities will be posted here.",
  followedYou: "followed you",
  commented: "commented",
  replied: "replied",
  commentPrev: "“[c]”",
  onYourPost: "on your post",
  onYourComment: "on your comment",
  likedYourPost: "liked your post.",
  likedYourComment: "liked your comment.",
  taggedYou: "tagged you",
  message: "Message",
  messages: "Messages",
  settings: "Settings",
  menu: "Menu",
  wtsup: "What's on your mind, [name] ?",
  chooseBackground: "Choose a background",
  removeBackground: "Remove background",
  author: "Author",
  post: "Post",
  aPost: "Post",
  posts: "Posts",
  postSuccess: "Your post has been published successfully.",
  postError: "Failed to publish your post. Please try again.",
  postDeleted: "Post deleted",
  unableToDeletePost: "Unable to delete the post. Please try again.",
  fileMaxSizeReached:
    "The file [name] has exceeded the maximum size of [size].",
  fileMaxLenReached: "You cannot upload more than [len] attachments at a time.",
  fileUploadError: "An error occurred while uploading the attachment.",
  whoToFollow: "Who to follow",
  noOneToFollow: "No suggestions",
  trending: "Trending",
  noTrends: "No trends",
  somethingWentWrong: "Something went wrong. Please try again.",
  friend: "Friend",
  friends: "Friends",
  follow: "Follow",
  following: "Following",
  followings: "Followings",
  follower: "Follower",
  followers: "Followers",
  followBack: "Follow back",
  unFollow: "Unfollow",
  forYou: "For you",
  noPostOnForYou: "We haven't found any good recommendations for you yet.",
  noPostOnFollowing:
    "No posts yet.  Follow people to see their public posts here",
  noPostOnProfile: "[name] has no public posts.",
  noBookmark: "You don't have any bookmark yet.",
  bookmarks: "Bookmarks",
  addToBookmarks: "Add to bookmarks",
  addedToBookmarks: "Added to bookmarks",
  removeFromBookmarks: "Remove from bookmarks",
  removedFromBookmarks: "Removed from bookmarks",
  dataError: "Something went wrong.",
  like: "Like",
  likes: "Likes",
  unLike: "I don't like anymore.",
  comment: "Comment",
  comments: "Comments",
  reply: "Reply",
  replies: "Replies",
  hideComments: "Hide comments",
  viewProfile: "View profile",
  viewUserSProfile: "View [name]'s profile",
  delete: "Delete",
  remove: "Remove",
  cancel: "Cancel",
  edit: "Edit",
  deleteConfirmPrompt:
    "Are you sure you want to delete this post ? You can't undo this action.",
  commentDeleteConfirmPrompt:
    "Are you sure you want to delete this comment ? You can't undo this action.",
  noLongerAvailablecomment: "The comment is no longer available",
  showPreviousComments: "Show previous comments",
  noComments: "No comments yet",
  commentAs: "Comment as [name]",
  replyTo: "Reply to [name]",
  toReply: "Reply",
  repliedByAuthor: "Replied by author",
  likedByAuthor: "Liked by author",
  invalidInput: "Invalid input. Please check your information",
  maxLenReached: "You have reached the character limit ([len] characters)",
  commentSent: "Comment sent",
  unaBleToSendComment: "Unable to send comment. Please try again.",
  commentDeleted: "Comment deleted",
  unableToDeleteComment: "Unable to delete comment. Please try again.",
  memberSince: "Member since",
  editProfile: "Edit Profile",
  profilePicture: "Profile picture",
  fullName: "Display name",
  yourFullName: "Your display name",
  bio: "Bio",
  tellUsAboutYou: "Tell us a little bit about yourself",
  save: "Save",
  clickToSelectImage: "Click to select an image",
  removePic: "Remove picture",
  profileUpdated: "Your profile has been successfully updated",
  profileUpdateError: "An error occurred while updating your profile",
  profilePicDeleted: "Your profile picture has been deleted",
  profilePicDeleteError:
    "Unable to delete your profile picture. Please try again.",
  crop: "Crop",
  cropImage: "Crop image",
  account: "Account",
  privacy: "Privacy and security",
  display: "Display",
  birthday: "Birthday",
  noBirthdate: "No birthdate. Please set your birthdate",
  updateBirthdate: "Update your birthdate",
  mustBeAtLeast13: "You must be at least 13 years old to use this service.",
  day: "Day",
  month: "Month",
  year: "Year",
  password: "Password",
  username: "Username",
  exportMyData: "Export my data",
  disableMyAccount: "Disable my account",
  deleteMyAccount: "Delete my account",
  onlineStatus: "Online status",
  unableToLoadChat: 'Unable to load chat "[name]"',
  waitEndOfOperation: "Wait for the end of the current operation",
  youCanChat: "You can now chat",
  // Reactions
  reactText: "React",
  reactions: "Reactions",
  tapToReact: "Tap or click to add a reaction",
  tapToUnreact: "Tap or click to remove",
  all: "All",
  add: "Add",
  addReaction: "Add a reaction",
  more: "More",
  copy: "Copy",
  // Chat content
  messageCopied: "Message copied to clipboard!",
  unableToCopyMessage: "Error while copying to clipboard!",
  unableToSendMessage: "Unable to send message",
  unableToSendThisMessage: "Unable to send this message. Please try again.",
  unableToDeleteMessage: "Unable to delete message. Please try again.",
  // Chat Header
  group: "Group",
  groupChat: "Group chat",
  online: "Online",
  activeText: "Active",
  created: "Created",
  addAMember: "Add -a member-",
  addMembers: "Add members",
  addDescription: "Add description",
  noDescription: "No description",
  thisAccountDeleted: "This account has been deleted",
  joined: "Joined",
  member: "Member",
  members: "Members",
  namesAndName: "[names] and [name]",
  namesAndOthers: "[names] and [len] others",
  availableUsers: "Available users",
  noAvailableUser: "No available user to add.",
  // Group chat
  cantSelectMoreUsers: "You can't select other users",
  unableToCreateGroup: "Impossible to create this group",
  mustSelectGroupUser: "You must select users to create a group",
  groupUpdated: "The group was successfully updated",
  groupUpdateError: "An error occurred while updating group settings",
  groupIconDeleted: "You have just deleted the group icon.",
  groupIconDeleteError: "Unable to remove group icon. Please try again.",
  seeAllMore: "See all ([len] more)",
  groupAddSuccess: "The selected users have been added",
  groupAddError: "You can't add new members to this group",
  removeFromGroup: "Remove from group",
  groupRemovePrompt: "You are about to delete [name] from [group]",
  banFromGroup: "Ban from group",
  groupBanPrompt: "You are about to ban [name] from [group]",
  groupBanInfo: "The other admins are authorized to reinstate the member",
  groupRemoveSuccess: "You removed [name] from [group]",
  groupRestoreSuccess: "You reinstated [name] to [group]",
  groupBanSuccess: "You suspended [name] from [group]",
  groupLeftSuccess: "You left [name]",
  changeGroupSettings: "Change group settings",
  groupIcon: "Group icon",
  groupName: "Group name",
  changeGroupName: "Change group name",
  groupDescription: "Group description",
  describeThisGroup: "Describe this group...",
  leave: "Leave",
  ban: "Ban",
  leaveAndDelete: "Leave and delete",
  leaveGroup: "Leave the group.",
  leaveGroupPrompt: "Are you sure you want to leave [name] ?",
  leaveGroupInfo:
    "If you leave without deleting the group the oldest member will receive your privileges",
  thisGroup: "This group",
  groupAdmin: "Admin",
  groupOwner: "Group owner",
  leftSince: "Left since",
  makeGroupAdmin: "Make group admin",
  dismissAsAdmin: "Dismiss as admin",
  // Chat List
  chats: "Chats",
  messagesOnApp: "Messages on OchoApp",
  selectChatToStart: "Select a chat to start.",
  newChat: "New chat",
  newGroup: "New group",
  noChat: "No chat available. Click [pen] to create a new chat",
  // New chat section
  startNewChat: "Start a new chat",
  wait: "Please wait",
  messageYourself: "Message yourself",
  suggestion: "Suggestion",
  suggestions: "Suggestions",
  create: "Create",
  showMore: "Show more",
  groupNameOptional: "Group name (optional)",
  hide: "Hide",
  // Room
  you: "You",
  newMember: "New member: [name]",
  youAddedMember: "You added [name] to the group.",
  addedYou: "[name] added you",
  addedMember: "[name] added [member] to the group",
  memberLeft: "[name] left the group",
  youRemovedMember: "You have removed [name] from the group.",
  removedYou: "[name] removed you",
  removedMember: "[name] removed [member] from the group",
  memberBanned: "[name] has been banned",
  youBannedMember: "You have banned [name] from the group.",
  bannedYou: "[name] banned you",
  bannedMember: "[name] banned [member] from the group",
  youCreatedGroup: "[name] created this group",
  createdGroup: "[name] created this group",
  canChatWithYou: "[name] can now chat with you",
  youReactedToYourMessage: "[name] reacted [r] to your [member]",
  youReactedToMessage: "[name] reacted [r] to [member]'s message",
  reactedToMessage: "[name] reacted [r] to your message",
  reactedMemberMessage: "[name] reacted [r] to [member]'s message",
  noPreview: "Start chatting ?",
  deletedChat: "Chat deleted",
  canNoLongerInteract: "You can no longer interact",
  noMessage: "No message",
  unavailableMessage: "Message not available",
  sent: "Sent",
  seenBy: "-Seen- by [name]",
  seenByAnd: "-Seen- by [names] and [name]",
  typeMessage: "Type a message...",
  // Verified
  verifiedUsers: "Verified users",
  veriFiedPrompt:
    "Verified badge accounts have been authenticated. These can be paid subscribers or notable people/brands.",
};
export type Vocabulary = typeof english;
export const french: Vocabulary = {
  welcomeIntro: "Un endroit où même -vous- pouvez trouver un ami.",
  login: "Connexion",
  signup: "Inscription",
  orContinueWith: "Ou continuer avec",
  newHere: "Je n'ai pas de compte ?",
  alreadyHave: "J'ai déjà un compte ?",
  register: "S'enregistrer",
  signIn: "Se connecter",
  createAccount: "Créer un compte",
  yourUsername: "Votre nom d'utilisateur",
  emailAdress: "Adresse email",
  exampleMail: "exemple@xyz.com",
  yourPassword: "Votre mot de passe",
  createPassword: "Créer un mot de passe pour votre securite",
  unsupportedEnv:
    "Environnement non supporté. Mettez à jour votre navigateur ou application, ou visitez le site officiel pour vous connecter.",
  appUser: "Utilisateur OchoApp",
  language: "Langue (language)",
  search: "Rechercher",
  searches: "Recherche",
  searchResultFor: 'Resultats de recherche pour "[q]".',
  noSearchResultFor: 'Aucun résultat pour "[q]".',
  searchEmptyKeyword: "Veuillez saisir des mots-clés dans votre recherche",
  tryNewSearch: "Essayez une nouvelle recherche.",
  users: "Utilisateurs",
  searchUsers: "Rechercher des utilisateurs",
  loggedIn: "Connecté(e) en tant que",
  profile: "Profil",
  theme: "Thème",
  systemDefault: "Système (défaut)",
  system: "Système",
  light: "Clair",
  dark: "Sombre",
  logout: "Déconnexion",
  home: "Accueil",
  explore: "Explorer",
  notifications: "Notifications",
  activity: "Activité",
  activityCenter: "Centre d'activité",
  noActivity: "Vos activités s'afficheront ici.",
  followedYou: "a commencé à te suivre.",
  commented: "a commenté",
  replied: "a repondu",
  commentPrev: "«[c]»",
  onYourPost: "à votre publication",
  onYourComment: "à votre commentaire",
  likedYourPost: "a aimé ta publication.",
  likedYourComment: "a aimé ton commentaire.",
  taggedYou: "vous a identifié",
  message: "Message",
  messages: "Messages",
  settings: "Paramètres",
  menu: "Menu",
  wtsup: "Quoi de neuf, [name] ?",
  chooseBackground: "Choisir un arrière-plan",
  removeBackground: "Rétirer l'arrière-plan",
  author: "Auteur",
  post: "Publier",
  aPost: "Publication",
  posts: "Publications",
  postSuccess: "Votre publilcation a été publié avec succès.",
  postError: "Echec de publilcation. Veuillez réessayer.",
  postDeleted: "Publication supprimé",
  unableToDeletePost:
    "Impossible de supprimer la publication. Veuillez réessayer.",
  fileMaxSizeReached: "Le fichier [name] dépassé la taille maximale de [size].",
  fileMaxLenReached:
    "Vous ne pouvez pas téléverser plus de [len] pièces jointes à la fois.",
  fileUploadError:
    "Une erreur est survenue lors du téléversement de la pièce jointe.",
  whoToFollow: "Suggestions pour vous",
  noOneToFollow: "Aucune suggestion pour le moment",
  trending: "Tendances",
  noTrends: "Aucune tendance pour le moment",
  somethingWentWrong: "Quelque chose n'a pas marché. Veuillez réessayer.",
  friend: "Ami(e)",
  friends: "Amis",
  follow: "Suivre",
  follower: "Follower",
  followers: "Followers",
  following: "Suivi(e)",
  followBack: "Suivre en retour",
  unFollow: "Ne plus suivre",
  forYou: "Pour toi",
  followings: "Suivis",
  noPostOnForYou:
    "Nous n'avons encore trouvé des bonnes recommendations pour vous.",
  noPostOnFollowing:
    "Aucune publication pour l'instant.\nSuivez des personnes pour voir leurs publications ici",
  dataError: "Quelque chose s'est mal passé.",
  noPostOnProfile: "[name] n'a aucune publication publique.",
  noBookmark: "Vous n'avez pas encore de favoris.",
  bookmarks: "Favoris",
  addToBookmarks: "Ajouter aux favoris",
  addedToBookmarks: "Ajoutée aux favoris",
  removeFromBookmarks: "Rétirer des favoris",
  removedFromBookmarks: "Rétirée des favoris",
  hideComments: "Masquer les commentaires",
  like: "J'aime",
  likes: "J'aime",
  unLike: "Je n'aime plus.",
  comment: "Commentaire",
  comments: "Commentaires",
  reply: "Reponse",
  replies: "Reponses",
  viewProfile: "Afficher le profil",
  viewUserSProfile: "Afficher le profil de [name]",
  delete: "Supprimer",
  remove: "Rétirer",
  cancel: "Annuler",
  edit: "Modifier",
  deleteConfirmPrompt:
    "Êtes-vous sûr de vouloir supprimer cette publication ? \nCette action est irréversible.",
  commentDeleteConfirmPrompt:
    "Êtes-vous sûr de vouloir supprimer ce commentaire ? \nCette action est irréversible.",
  noLongerAvailablecomment: "Le commentaire n'est plus diaponible",
  showPreviousComments: "Afficher les commentaires precedents",
  noComments: "Aucun commentaire à afficher",
  commentAs: "Commenter en tant que [name]",
  replyTo: "Répondre à [name]",
  toReply: "Répondre",
  repliedByAuthor: "L'auteur a répondu",
  likedByAuthor: "Aimé par l'auteur",
  invalidInput: "Entrée incorrecte. Veuillez vérifier vos informations",
  maxLenReached: "Vous avez atteint la limite de caractères ([len] caractères)",
  commentSent: "Commentaire envoyé",
  unaBleToSendComment:
    "Impossible d'envoyer le commentaire. Veuillez réessayer.",
  commentDeleted: "Commentaire supprimé",
  unableToDeleteComment:
    "Impossible de supprimer le commentaire. Veuillez réessayer.",
  memberSince: "Membre depuis",
  editProfile: "Modifier le profil",
  profilePicture: "Photo de profil",
  fullName: "Nom complet",
  yourFullName: "Votre nom complet",
  bio: "Bio",
  tellUsAboutYou: "Parlez nous un peu de vous",
  save: "Enregistrer",
  clickToSelectImage: "Cliquez pour selectioner une image",
  removePic: "Supprimer la photo",
  profileUpdated: "Votre profil a été mis à jour avec succèss",
  profileUpdateError:
    "Une erreur est survenue lors de la mise à jour de votre profil",
  profilePicDeleted: "Votre photo de profil a été supprimée",
  profilePicDeleteError:
    "Impossible de supprimer votre photo de profil. Veuillez réessayer.",
  crop: "Rogner",
  cropImage: "Rogner l'image",
  account: "Compte",
  privacy: "Confidentialité et sécurité",
  display: "Affichage",
  birthday: "Date de naissance",
  noBirthdate: "Aucune date de naissance. Veuillez définir votre date de naissance",
  updateBirthdate: "Mettre à jour votre date de naissance",
  mustBeAtLeast13:"Vous devez avoir au moins 13 ans pour utiliser ce service.",
  day: "Jour",
  month: "Mois",
  year: "Année",
  password: "Mot de passe",
  username: "Nom d'utilisateur",
  exportMyData: "Exporter mes données",
  disableMyAccount: "Désactiver mon compte",
  deleteMyAccount: "Supprimer mon compte",
  onlineStatus: "Statut en ligne",
  unableToLoadChat: 'Impossible de charger la discussion "[name]"',
  waitEndOfOperation: "Patientez la fin de l'opération en cours",
  youCanChat: "Vous pouvez maintenant discuter",
  // Reactions
  reactText: "Réagir",
  reactions: "Réactions",
  tapToReact: "Appuyez ou cliquez pour ajouter une réaction",
  tapToUnreact: "Appuyez ou cliquez pour supprimer",
  all: "Tout",
  add: "Ajouter",
  addReaction: "Ajouter une réaction",
  more: "Plus",
  copy: "Copier",
  // Chat content
  messageCopied: "Message copié dans le presse-papiers !",
  unableToCopyMessage: "Erreur lors de la copie dans le presse-papiers !",
  unableToSendMessage: "Impossible d'envoyer un message",
  unableToSendThisMessage:
    "Impossible d'envoyer ce message. Veuillez réessayer.",
  unableToDeleteMessage:
    "Impossible de supprimer le message. Veuillez réessayer.",
  // Chat Header
  group: "Groupe",
  groupChat: "Groupe de discussion",
  online: "En ligne",
  activeText: "Actif",
  created: "Créé",
  addAMember: "Ajouter -un membre-",
  addMembers: "Ajouter des membres",
  addDescription: "Ajouter une description",
  noDescription: "Aucune description",
  thisAccountDeleted: "Ce compte a été supprimé",
  joined: "A rejoint",
  member: "Member",
  members: "Members",
  namesAndName: "[names] et [name]",
  namesAndOthers: "[names] et [len] autres",
  availableUsers: "Utilisateurs disponibles",
  noAvailableUser: "Nous n'avons pas trouvé d'utilisateur à ajouter.",
  // Group chat
  cantSelectMoreUsers: "Vous ne pouvez pas selectionner d'autres utilisateurs",
  unableToCreateGroup: "Impossible de creer ce groupe",
  mustSelectGroupUser:
    "Vous devez sélectionner des utilisateurs pour créer un groupe",
  groupUpdated: "Le groupe a été mis à jour avec succèss",
  groupUpdateError:
    "Une erreur est survenue lors de la mise à jour des paramètres du groupe",
  groupIconDeleted: "Vous venez de supprimer l'icône du groupe.",
  groupIconDeleteError:
    "Impossible de supprimer l'icône du groupe. Veuillez réessayer.",
  seeAllMore: "Tout voir ([len] de plus)",
  groupAddSuccess: "Les utilisateurs selectionnes ont bien été ajoutés",
  groupAddError: "Vous ne pouvez pas ajouter de nouveaux membres à ce groupe",
  removeFromGroup: "Retirer du groupe",
  groupRemovePrompt: "Vous êtes sur le point de supprimer [name] de [group]",
  banFromGroup: "Suspendre",
  groupBanPrompt: "Vous êtes sur le point de bannir [name] de [group]",
  groupBanInfo: "Les autres administrateurs peuvent reintegrer le membre",
  groupRemoveSuccess: "Vous avez retiré [name] de [group]",
  groupRestoreSuccess: "Vous avez réintegré [name] à [group]",
  groupBanSuccess: "Vous avez suspendu [name] de [group]",
  groupLeftSuccess: "Vous avez quitté [name]",
  changeGroupSettings: "Modifier les paramètres du groupe",
  groupIcon: "Icône de groupe",
  groupName: "Nom du groupe",
  changeGroupName: "Changer le nom du groupe",
  groupDescription: "Description du groupe",
  describeThisGroup: "Decrivez ce groupe...",
  leave: "Quitter",
  ban: "Suspendre",
  leaveAndDelete: "Quitter et supprimer",
  leaveGroup: "Quitter le groupe.",
  leaveGroupPrompt: "Êtes-vous sûr de vouloir quitter [name] ?",
  leaveGroupInfo:
    "Si vous quittez sans supprimer le groupe le membre le plus ancien recevra vos privileges",
  thisGroup: "Ce groupe",
  groupAdmin: "Admin",
  groupOwner: "Proprietaire",
  leftSince: "A quitté depuis",
  makeGroupAdmin: "Nommer admin",
  dismissAsAdmin: "Supprimer des admins",
  // Chat List
  chats: "Discussions",
  messagesOnApp: "Messages sur OchoApp",
  selectChatToStart: "Sélectionnez une discussion pour commencer.",
  newChat: "Nouvelle discussion",
  newGroup: "Nouveau groupe",
  noChat:
    "Aucune discussion disponible. Cliquez sur [pen] pour créer une nouvelle discussion",
  // New chat section
  startNewChat: "Démarrer une nouvelle discussion",
  wait: "Patientez",
  messageYourself: "Envoyez-vous un message",
  suggestion: "Suggestion",
  suggestions: "Suggestions",
  create: "Créer",
  showMore: "Afficher plus",
  hide: "Masquer",
  groupNameOptional: "Nom du groupe (facultatif)",
  // Room
  you: "Vous",
  newMember: "Nouveau membre : [name]",
  youAddedMember: "Vous avez ajouté [name] au groupe.",
  addedYou: "[name] vous a ajouté",
  addedMember: "[name] a ajouté [member] au groupe.",
  memberLeft: "[name] a quitté le groupe",
  youRemovedMember: "Vous avez retiré [name] du groupe.",
  removedYou: "[name] vous a retiré",
  removedMember: "[name] a retiré [member] du groupe.",
  memberBanned: "[name] a été suspendu",
  youBannedMember: "Vous avez suspendu [name] du groupe.",
  bannedYou: "[name] vous a suspendu",
  bannedMember: "[name] a suspendu [member] du groupe.",
  youCreatedGroup: "[name] avez créé ce groupe.",
  createdGroup: "[name] a créé ce groupe.",
  canChatWithYou: "[name] peut maintenant discuter avec vous",
  youReactedToYourMessage: "[name] avez réagi [r] à votre message",
  youReactedToMessage: "[name] avez réagi [r] au message de [member]",
  reactedToMessage: "[name] a réagi [r] à votre message",
  reactedMemberMessage: "[name] a réagi  [r] au message de [member]",
  noPreview: "Discuter ?",
  deletedChat: "Discussion supprimée",
  canNoLongerInteract: "Vous ne pouvez plus interagir",
  noMessage: "Aucun message",
  unavailableMessage: "Message non disponibe",
  sent: "Envoyé",
  seenBy: "-Vu- par [name]",
  seenByAnd: "-Vu- par [names] et [name]",
  typeMessage: "Écrivez un message...",
  // Verified
  verifiedUsers: "Utilisateurs certifiés",
  veriFiedPrompt:
    "Les comptes avec un badge Vérifié ont été authentifiés. Il peut s’agir de personnes payant un abonnement ou de personnes ou de marques notables.",
};

export const vocabulary = {
  en: english,
  fr: french,
};

export type VocabularyKey = keyof Vocabulary;
export type Language = keyof typeof vocabulary;

export const allVocabularyKeys = Object.keys(english) as VocabularyKey[];

// Fonction pour récupérer les valeurs de `vocabulary` et en faire un type
export function getVocabularyObject<K extends VocabularyKey>(
  keys: K[] = allVocabularyKeys as K[],
): Record<K, string> {
  const result: Partial<Record<K, string>> = {};
  keys.forEach((key) => {
    if (key in vocabulary.en) {
      result[key] = vocabulary.en[key];
    }
  });
  return result as Record<K, string>;
}

const vocabularyObject = getVocabularyObject();
export type VocabularyObject = typeof vocabularyObject;
