export const english = {
    search: "Search",
    searches: "Search",
    loggedIn: "Logged in as",
    profile: "Profile",
    theme: "Theme",
    systemDefault: "System (default)",
    light: "Light",
    dark: "Dark",
    logout: "Logout",
    home: "Home",
    explore: "Explore",
    notifications: "Notifications",
    activity: "Activity",
    activityCenter: "Activity Center",
    message: "Message",
    messages: "Messages",
    settings: "Settings",
    menu: "Menu",
    wtsup: "What's up ?",
    chooseBackground: "Choose a background",
    removeBackground: "Remove background",
    post: "Post",
    aPost: "Post",
    posts: "Posts",
    whoToFollow: "Who to follow",
    noOneToFollow: "No suggestions",
    trending: "Trending",
    noTrends: "No trends",
    somethingWentWrong: "Something went wrong. Please try again.",
    friend: "Friend",
    follow: "Follow",
    following: "Following",
    followBack: "Follow back",
    unFollow: "Unfollow",
    forYou: "For you",
    followings: "Following",
    noPostOnForYou: "We haven't found any good recommendations for you yet.",
    noPostOnFollowing: "No posts yet.  Follow people to see their public posts here",
    noPostOnProfile: "[name] has no public posts.",
    noBookmark: "You don't have any bookmark yet.",
    dataError: "Something went wrong.",
    like: "Like",
    likes: "Likes",
    unLike: "I don't like anymore.",
    comment: "Comment",
    comments: "Comments",
    hideComments: "Hide comments",
    viewUserSProfile: "View [name]'s profile",
    delete: "Delete",
    cancel: "Cancel",
    edit: "Edit",
    deleteConfirmPrompt: "Are you sure you want to delete this post? You can't undo this action.",
    addToBookmarks: "Add to bookmarks",
    addedToBookmarks: "Added to bookmarks",
    removeFromBookmarks: "Remove from bookmarks",
    removedFromBookmarks: "Removed from bookmarks",
}
export const french = {
    search: "Rechercher",
    searches: "Recherche",
    loggedIn: "Connecté(e) en tant que",
    profile: "Profil",
    theme: "Thème",
    systemDefault: "Système (défaut)",
    light: "Clair",
    dark: "Sombre",
    logout: "Déconnexion",
    home: "Accueil",
    explore: "Explorer",
    notifications: "Notifications",
    activity: "Activité",
    activityCenter: "Centre d'activité",
    message: "Message",
    messages: "Messages",
    settings: "Paramètres",
    menu: "Menu",
    wtsup: "Quoi de neuf ?",
    chooseBackground: "Choisir un arrière-plan",
    removeBackground: "Rétirer l'arrière-plan",
    post: "Publier",
    aPost: "Publication",
    posts: "Publications",
    whoToFollow: "Suggestions pour vous",
    noOneToFollow: "Aucune suggestion pour le moment",
    trending: "Tendances",
    noTrends: "Aucune tendance pour le moment",
    somethingWentWrong: "Quelque chose n'a pas marché. Veuillez réessayer.",
    friend: "Ami(e)",
    follow: "Suivre",
    following: "Suivi(e)",
    followBack: "Suivre en retour",
    unFollow: "Ne plus suivre",
    forYou: "Pour toi",
    followings: "Suivis",
    noPostOnForYou: "Nous n'avons encore trouvé des bonnes recommendations pour vous.",
    noPostOnFollowing: "Aucune publication pour l'instant.\nSuivez des personnes pour voir leurs publications ici",
    dataError: "Quelque chose s'est mal passé." ,
    noPostOnProfile: "[name] n'a aucune publication publique.",
    noBookmark: "Vous n'avez pas encore de favoris.",
    hideComments: "Masquer les commentaires",
    like: "J'aime",
    likes: "J'aime",
    unLike: "Je n'aime plus.",
    comment: "Commentaire",
    comments: "Commentaires",
    viewUserSProfile: "Afficher le profil de [name]",
    delete: "Supprimer",
    cancel: "Annuler",
    edit: "Modifier",
    deleteConfirmPrompt: "Êtes-vous sûr de vouloir supprimer cette publication ? \nCette action est irréversible.",
    addToBookmarks: "Ajouter aux favoris",
    addedToBookmarks: "Ajoutée aux favoris",
    removeFromBookmarks: "Rétirer des favoris",
    removedFromBookmarks: "Rétirée des favoris",
}

export const vocabulary = {
    en: english,
    fr: french,
}

export type Vocabulary = typeof vocabulary.en;
export type VocabularyKey = keyof Vocabulary;
export type Language = keyof typeof vocabulary;